version: '3.8'

services:
  # Serviço do Banco de Dados
  linguados-db:
    image: mysql:8.0
    container_name: linguados-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - linguados-net

  # Serviço do Ollama (Inteligência Artificial Local)
  linguados-ai:
    image: ollama/ollama:latest
    container_name: linguados-ai
    restart: always
    ports:
      - "11435:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - linguados-net
    deploy:
      resources:
        limits:
          memory: 3G

  linguados-ai-miner:
    image: alpine:latest
    container_name: linguados-ai-miner
    depends_on:
      - linguados-ai
    networks:
      - linguados-net
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        echo "A aguardar que o servidor Ollama fique online..."
        while ! nc -z linguados-ai 11434; do
          sleep 1
        done
        echo "Ollama online! A iniciar o download automatico do modelo ${LOCAL_AI_MODEL}..."
        apk add --no-cache curl
        curl -X POST http://linguados-ai:11434/api/pull -d "{\"name\": \"${LOCAL_AI_MODEL}\"}"
        echo "Download do modelo concluido com sucesso!"

  # Serviço da Aplicação
  linguados-app:
    build: .
    container_name: linguados-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=linguados-db
      - DB_PORT=${DB_PORT}
      - AI_MODEL=${LOCAL_AI_MODEL}
    depends_on:
      linguados-db:
        condition: service_started
      linguados-ai-miner:
        condition: service_completed_successfully
    networks:
      - linguados-net

networks:
  linguados-net:
    driver: bridge

volumes:
  ollama-data: