services:
  # Serviço do Banco de Dados
  linguados-db:
    image: mysql:8.0
    container_name: linguados-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linguados
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - linguados-net

  # Serviço da Aplicação (Tomcat 10)
  linguados-app:
    build: .
    container_name: linguados-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=linguados-db
      - DB_PORT=3306
    depends_on:
      - linguados-db
    networks:
      - linguados-net

networks:
  linguados-net:
    driver: bridge