version: "3.8"

services:
  db:
    image: mysql:8
    container_name: linguados_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linguados
    ports:
      - "3307:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: linguados-app
    depends_on:
      - db
    ports:
      - "8080:8080"